# Problem 17: Is Vector exception-safe?

Consider:
```c++
template <typename T> class vector {
	size_t n, cap;
	T *theVector;
public:
	vector (size_t n, const T &x): 
		n{n}, cap{n}, theVector{static_cast<T*>(operator new(n * sizeof(T)))} {
		for (size_t i = 0; i < n; ++i) {
			new (theVector + i) T(x);
			// What if the copy constructor - T(x) - throws?
		}	
	}
};
```
What if the copy constructor - T(x) - throws?
- Partially constructed vector - destructor will not run.
- Broken invariant - don't have n valid items.
<u>Note</u>: If operator new throws, nothing has been allocated - no problem - strong guarantee.

<u>Fix</u> 
```c++
vector (size_t n, const T &x):
	n{0}, cap{n}, theVector {static_cast ...} {
	try {
		while (this->n < cap) {
			new (theVector + this->n) T(x);
			++this->n;
		}
	}
	catch (...)	{ // catch anything
		while (this->n > 0) {
			theVector[this->n - 1].~T();
			--this->n;
		}
		operator delete(theVector);
		throw; // rethrow the exception
	}
}
```

Let's abstract the filling part into its own function.
```c++
template <typename T> void uninitialized_file(T* start, T* finish, const T &x) {
	T* p;
	try {
		for (p = start; p != finish; ++p) {
			new (p) T(x);
		}
	}
	catch (...) {
		for (T* q = p; q != start; --q)
			(q - 1)->~T();
			throw;
	}
}

vector(size_t n, const T &x):
	n{n}, cap{n}, theVector{static_cast ... } {
	try {
		uninitialized_fill(theVector, theVector + n, x);
	}	
	catch(...) {
		operator delete(theVector);
		throw;
	}
}
```


Can clean this up by using RAII on the array:
```c++
template <typename T> struct vector_base {
	size_t cap;
	T* v;
	vector_base(size_t n): 
		cap{n}, v{static_cast<T*>(operator new(n * sizeof(T)))} { }
	~vector_base() {operator delete(v);}
}

template <typename T> class vector {
	vector_base<T> vb;
	size_t n;
public:
	vector(size_t n, const T &x):
		vb{n}, n{n} {
		unitialized_fill(vb.b, vb.b + n, x);
	}
	...
	~vector() {
		clear();
	}
}
```

Copy constructor:
```c++
template <typename T> vector<T>::vector(const vector &other):
	vb{other.size}, n{other.n} {
	uninitialized_copy(vb.v, vb.b + n, other.begin());
	// similar to uninitialized_fill, details as exercise.
}
```

\
<u>Assignment</u>:
Copy + Swap is exception safe.


Push_back:
```c++
void push_back(const T &x) {
	increaseCap();
	new (vb.v + n) T(x);
	// If throws, have the same vector
	++n;
	// Don't increment n before you know the construction succeeded
}
```